- project:
    merge-mode: squash-merge
    templates:
      - publish-to-pypi
    check:
      jobs:
        - otc-tox-pep8
        - otc-tox-py311
    gate:
      jobs:
        - otc-tox-pep8
        - otc-tox-py311
